import React, { useState } from "react";
import { FiTool, FiCheckCircle, FiXCircle, FiEye, FiArrowRight, FiShield, FiZap, FiAlertTriangle } from "react-icons/fi";

/**
 * Replanning Panel Component
 * Displays intelligent recovery options generated by the replanning engine,
 * with factual rationales, evidence points, and approval/preview triggers.
 */
const ReplanningPanel = ({
  proposals = [],
  onGenerate,
  onPreview,
  onApprove,
  onReject,
  isLoading = false
}) => {
  const [selectedStrategy, setSelectedStrategy] = useState("ALL");

  const getStrategyBadge = (strategy) => {
    switch (strategy) {
      case "DEADLINE_RECOVERY":
        return <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-red-100 text-red-700 dark:bg-red-950/40 dark:text-red-300">DEADLINE RECOVERY</span>;
      case "WORKLOAD_BALANCING":
        return <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-blue-100 text-blue-700 dark:bg-blue-950/40 dark:text-blue-300">WORKLOAD BALANCING</span>;
      case "BOTTLENECK_RELIEF":
        return <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-purple-100 text-purple-700 dark:bg-purple-950/40 dark:text-purple-300">BOTTLENECK RELIEF</span>;
      case "SEQUENCE_OPTIMIZATION":
        return <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-emerald-100 text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-300">SEQUENCE OPTIMIZATION</span>;
      default:
        return <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-slate-100 text-slate-700 dark:bg-slate-700 dark:text-slate-300">{strategy}</span>;
    }
  };

  const getStatusBadge = (status) => {
    switch (status) {
      case "APPROVED":
        return <span className="px-2 py-0.5 rounded-full text-xs font-semibold bg-emerald-100 text-emerald-700 dark:bg-emerald-950/50 dark:text-emerald-300">Approved</span>;
      case "EXECUTED":
        return <span className="px-2 py-0.5 rounded-full text-xs font-semibold bg-indigo-100 text-indigo-700 dark:bg-indigo-950/50 dark:text-indigo-300">Executed</span>;
      case "STALE":
        return <span className="px-2 py-0.5 rounded-full text-xs font-semibold bg-red-100 text-red-700 dark:bg-red-950/50 dark:text-red-300">Outdated (Stale)</span>;
      case "REJECTED":
        return <span className="px-2 py-0.5 rounded-full text-xs font-semibold bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-400">Rejected</span>;
      default:
        return <span className="px-2 py-0.5 rounded-full text-xs font-semibold bg-amber-100 text-amber-700 dark:bg-amber-950/50 dark:text-amber-300">Proposed</span>;
    }
  };

  return (
    <div className="bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 shadow-sm p-6 space-y-6">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 pb-4 border-b border-slate-100 dark:border-slate-700">
        <div>
          <h3 className="text-lg font-bold text-slate-900 dark:text-white flex items-center gap-2">
            <FiTool className="w-5 h-5 text-indigo-600 dark:text-indigo-400" />
            Intelligent Replanning Engine
          </h3>
          <p className="text-sm text-slate-500 dark:text-slate-400">
            Algorithmic proposal candidates to recover slipped deadlines and balance pressure.
          </p>
        </div>

        {/* Generator Controls */}
        <div className="flex items-center gap-3">
          <select
            value={selectedStrategy}
            onChange={(e) => setSelectedStrategy(e.target.value)}
            className="px-3 py-2 text-xs bg-slate-50 dark:bg-slate-900 border border-slate-300 dark:border-slate-600 rounded-lg text-slate-800 dark:text-slate-200"
          >
            <option value="ALL">All Strategies</option>
            <option value="DEADLINE_RECOVERY">Deadline Recovery</option>
            <option value="WORKLOAD_BALANCING">Workload Balancing</option>
            <option value="BOTTLENECK_RELIEF">Bottleneck Relief</option>
            <option value="SEQUENCE_OPTIMIZATION">Sequence Optimization</option>
          </select>

          <button
            onClick={() => onGenerate && onGenerate(selectedStrategy)}
            disabled={isLoading}
            className="inline-flex items-center gap-2 px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-semibold rounded-lg shadow-sm transition-colors disabled:opacity-60"
          >
            <FiZap className="w-3.5 h-3.5" />
            {isLoading ? "Analyzing Graph..." : "Generate Proposals"}
          </button>
        </div>
      </div>

      {/* Proposals List */}
      {proposals.length === 0 ? (
        <div className="py-12 text-center">
          <FiTool className="w-10 h-10 text-slate-300 dark:text-slate-600 mx-auto mb-3" />
          <p className="text-sm font-semibold text-slate-700 dark:text-slate-300">
            No replanning proposals currently generated.
          </p>
          <p className="text-xs text-slate-500 dark:text-slate-400 mt-1 max-w-sm mx-auto">
            Click "Generate Proposals" to evaluate schedule recovery opportunities across the dependency network.
          </p>
        </div>
      ) : (
        <div className="space-y-4">
          {proposals.map((proposal) => {
            const isStale = proposal.status === "STALE";
            const isExecuted = proposal.status === "EXECUTED";
            const isApproved = proposal.status === "APPROVED";

            return (
              <div
                key={proposal.proposalId}
                className={`p-5 rounded-xl border transition-all ${
                  isStale
                    ? "border-red-200 bg-red-50/20 dark:border-red-900/40"
                    : isExecuted
                    ? "border-indigo-200 bg-indigo-50/20 dark:border-indigo-900/40"
                    : isApproved
                    ? "border-emerald-200 bg-emerald-50/20 dark:border-emerald-900/40"
                    : "border-slate-200 dark:border-slate-700 hover:border-slate-300 dark:hover:border-slate-600"
                }`}
              >
                <div className="flex flex-col md:flex-row md:items-center justify-between gap-2 mb-3">
                  <div className="flex items-center gap-2.5">
                    {getStrategyBadge(proposal.strategy)}
                    <h4 className="text-base font-bold text-slate-900 dark:text-white">
                      {proposal.title}
                    </h4>
                  </div>
                  <div>{getStatusBadge(proposal.status)}</div>
                </div>

                <p className="text-xs text-slate-600 dark:text-slate-300 mb-4">
                  {proposal.rationale}
                </p>

                {/* Projected Impact & Proposed Changes Grid */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
                  {/* Proposed Changes */}
                  <div className="p-3 bg-slate-50 dark:bg-slate-900/60 rounded-lg border border-slate-100 dark:border-slate-800">
                    <span className="text-xs font-bold text-slate-600 dark:text-slate-400 uppercase tracking-wider block mb-2">
                      Proposed Changes ({proposal.proposedChanges?.length || 0})
                    </span>
                    <ul className="text-xs text-slate-700 dark:text-slate-300 space-y-1.5">
                      {(proposal.proposedChanges || []).map((ch, idx) => (
                        <li key={idx} className="flex items-start gap-1.5">
                          <span className="text-indigo-600 font-bold">•</span>
                          <span>{ch.details || `${ch.type} on ${ch.taskTitle || ch.taskId}`}</span>
                        </li>
                      ))}
                    </ul>
                  </div>

                  {/* Impact Summary */}
                  <div className="p-3 bg-slate-50 dark:bg-slate-900/60 rounded-lg border border-slate-100 dark:border-slate-800">
                    <span className="text-xs font-bold text-slate-600 dark:text-slate-400 uppercase tracking-wider block mb-2">
                      Expected Impact
                    </span>
                    <div className="text-xs space-y-1 text-slate-700 dark:text-slate-300">
                      {proposal.projectedImpact?.health && (
                        <div>
                          Health Score: <span className="font-semibold">{proposal.projectedImpact.health.before} → {proposal.projectedImpact.health.after}</span>
                        </div>
                      )}
                      {proposal.projectedImpact?.criticalTasks && (
                        <div>
                          Critical Tasks: <span className="font-semibold">{proposal.projectedImpact.criticalTasks.before} → {proposal.projectedImpact.criticalTasks.after}</span>
                        </div>
                      )}
                      {proposal.projectedImpact?.bottlenecks && (
                        <div>
                          Bottlenecks: <span className="font-semibold">{proposal.projectedImpact.bottlenecks.before} → {proposal.projectedImpact.bottlenecks.after}</span>
                        </div>
                      )}
                    </div>
                  </div>
                </div>

                {/* Stale Warning Banner */}
                {isStale && (
                  <div className="p-2.5 mb-3 bg-red-50 dark:bg-red-950/30 border border-red-200 dark:border-red-900/40 rounded-lg flex items-center gap-2 text-xs text-red-700 dark:text-red-300">
                    <FiAlertTriangle className="w-4 h-4 shrink-0" />
                    <span>Project state changed after this proposal was generated. Please regenerate fresh proposals.</span>
                  </div>
                )}

                {/* Action Buttons */}
                <div className="flex items-center justify-end gap-2 pt-2 border-t border-slate-100 dark:border-slate-700/60">
                  <button
                    onClick={() => onPreview && onPreview(proposal)}
                    className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold text-slate-700 dark:text-slate-200 bg-slate-100 dark:bg-slate-700 hover:bg-slate-200 dark:hover:bg-slate-600 rounded-lg transition-colors"
                  >
                    <FiEye className="w-3.5 h-3.5" />
                    Review Diff
                  </button>

                  {proposal.status === "PROPOSED" && (
                    <>
                      <button
                        onClick={() => onReject && onReject(proposal.proposalId)}
                        className="inline-flex items-center gap-1 px-3 py-1.5 text-xs font-semibold text-slate-600 hover:text-red-600 transition-colors"
                      >
                        <FiXCircle className="w-3.5 h-3.5" />
                        Reject
                      </button>

                      <button
                        onClick={() => onApprove && onApprove(proposal)}
                        className="inline-flex items-center gap-1.5 px-3.5 py-1.5 text-xs font-bold text-white bg-indigo-600 hover:bg-indigo-700 rounded-lg shadow-sm transition-colors"
                      >
                        <FiCheckCircle className="w-3.5 h-3.5" />
                        Approve & Apply
                      </button>
                    </>
                  )}

                  {proposal.status === "APPROVED" && (
                    <button
                      onClick={() => onApprove && onApprove(proposal)}
                      className="inline-flex items-center gap-1.5 px-3.5 py-1.5 text-xs font-bold text-white bg-emerald-600 hover:bg-emerald-700 rounded-lg shadow-sm transition-colors"
                    >
                      <FiCheckCircle className="w-3.5 h-3.5" />
                      Apply Approved Plan
                    </button>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
};

export default ReplanningPanel;
